Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Abstract;
using WebApplication1.Entities;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        private IProductRepository productRepository { get; set; }
        public AdminController(IProductRepository productRepo)
        {
            productRepository = productRepo;
        }
        // GET: Admin
        public ViewResult ProductList(int page = 1)
        {
            int pageSize = 1;

            ProductIndexViewModel model = new ProductIndexViewModel();
            model.Products = productRepository.Products
                .OrderByDescending(x => x.ProductId)
                .Skip((page - 1) * pageSize)
                .Take(pageSize)
                .ToList();

            model.PagingInfo = new PagingInfo()
            {
                CurrentPage = page,
                ItemsPerPage = pageSize,
                TotalItems = productRepository.Products.Count()
            };

            var userName = User.Identity.Name;

            return View(model);
        }

        public ViewResult ProductAdd()
        {
            //Sử dụng ViewBag để truyền dữ liệu từ controller sang view
            ViewBag.Categories = productRepository.Categories.ToList();

            return View();
        }

        public ViewResult ProductEdit(int id)
        {
            ViewBag.Categories = productRepository.Categories.ToList();

            Product product = productRepository
                .Products
                .FirstOrDefault(x => x.ProductId == id);

            return View(product);
        }

        public ActionResult ProductDelete(int id)
        {
            return RedirectToAction("ProductList");
        }

        [HttpPost]
        public ActionResult ProductAdd(Product model)
        {
            if (ModelState.IsValid)
            {
                //lưu thông tin sản phẩm vào cơ sở dữ liệu
                productRepository.Save(model);
                //truyền thông báo lên view
                TempData["msg"] = "Thêm mới sản phẩm thành công";
                //chuyển về trang danh sách sản phẩm
                return RedirectToAction("ProductList");
            }
            else
            {
                TempData["msg"] = "Vui lòng cung cấp đủ thông tin sản phẩm";
                //Tạo lại danh sách danh mục sản phẩm
                ViewBag.Categories = productRepository.Categories.ToList();
                //Truyền lại dữ liệu dữ liệu người dùng nhập trên view ProductAdd
                return View(model);
            }
        }

        [HttpPost]
        public ActionResult ProductEdit(Product model)
        {
            if (ModelState.IsValid)
            {
                //lưu thông tin sản phẩm vào cơ sở dữ liệu
                productRepository.Save(model);
                //truyền thông báo lên view
                TempData["msg"] = "Cập nhật sản phẩm thành công";
                //chuyển về trang danh sách sản phẩm
                return RedirectToAction("ProductList");
            }
            else
            {
                TempData["msg"] = "Vui lòng cung cấp đủ thông tin sản phẩm";
                //Tạo lại danh sách danh mục sản phẩm
                ViewBag.Categories = productRepository.Categories.ToList();
                //Truyền lại dữ liệu dữ liệu người dùng nhập trên view ProductEdit
                return View(model);
            }
        }
    }
}

Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Abstract;
using WebApplication1.Entities;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class CartController : Controller
    {
        private IProductRepository productRepository;
        private IOrderProcessor orderProcessor;

        public CartController(IProductRepository repo, IOrderProcessor orderPara)
        {
            productRepository = repo;
            orderProcessor = orderPara;
        }
        
        public RedirectToRouteResult AddToCart(Cart cart, int productId, string returnUrl)
        {
            Product product = productRepository.Products
                .FirstOrDefault(p => p.ProductId == productId);

            if (product != null)
            {
                cart.AddItem(product, 1);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToRouteResult RemoveFromCart(Cart cart, int productId, string returnUrl)
        {
            Product product = productRepository.Products
                .FirstOrDefault(p => p.ProductId == productId);

            if (product != null)
            {
                cart.RemoveLine(product);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public PartialViewResult SummaryCart(Cart cart)
        {
            return PartialView(cart);
        }

        public ViewResult Index(Cart cart, string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }

        [HttpPost]
        public ActionResult UpdateQuantity(Cart cart, int productId , int quantity, string returnUrl)        
        {
            cart.UpdateQuantityByProductID(new Product { ProductId = productId }, quantity);
            return RedirectToAction("Index", new { returnUrl });
        }

        public ViewResult Checkout()
        {
            return View(new ShippingDetails());
        }

        [HttpPost]
        public ActionResult Checkout(Cart cart, ShippingDetails shippingDetails)
        {
            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Vui lòng chọn thêm sản phẩm");
            }

            if (ModelState.IsValid)
            {
                //Xử lý đơn hàng: Lưu vào CSDL, gửi email
                orderProcessor.ProcessOrder(cart, shippingDetails);
                //xóa thông tin giỏ hàng
                cart.Clear();
                //chuyển người dùng đến view thông báo hoàn tất đặt hàng
                return View("Completed");
            }
            else
            {
                return View(shippingDetails);
            }
        }        
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <!--CORE Bootstrap CSS-->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <header>
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <div class="page-header">Header</div>
                </div>
            </div>
        </div>
    </header>
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-md-2">
                <ul class="list-group">
                    <li class="list-group-item">
                        <a href="/">
                            <i class="glyphicon glyphicon-arrow-left"></i>
                            Về trang chủ
                        </a>
                    </li>
                    <li class="list-group-item">
                        <a href="@Url.Action("ProductList","Admin")">
                            Danh sách sản phẩm
                        </a>
                    </li>
                    <li class="list-group-item">
                        <a href="#" onclick="alert('Độc giả tự cài đặt'); return false">
                            Danh mục sản phẩm
                        </a>
                    </li>
                    <li class="list-group-item">
                        <a href="#" onclick="alert('Độc giả tự cài đặt'); return false">
                            Danh mục đơn hàng
                        </a>
                    </li>
                    <li class="list-group-item">
                        @using (Html.BeginForm("LogOff", "Account", FormMethod.Post))
                        {
                            @Html.AntiForgeryToken()
                            <button type="submit" class="btn btn-primary">Đăng xuất</button>
                        }
                    </li>
                </ul>
            </div>
            <div class="col-xs-12 col-md-10">
                <!--Hiển thị thông báo-->
                @if (TempData["msg"] != null)
                {
                    <div class="alert alert-info">
                        <p>
                            @TempData["msg"]
                        </p>
                    </div>
                }
                @RenderBody()
            </div>
        </div>
    </div>
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <p>Bản quyền &copy; 2017 - vanvuong2610@@gmail.com - Học viện MSITA</p>
                </div>
            </div>
        </div>

    </footer>
    <!--Javascript Library-->
    <script src="~/Scripts/jquery-3.1.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    @RenderSection("js", false)
</body>
</html>

Views/Shared/_LayoutHome.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <!--CORE Bootstrap CSS-->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <header>
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <div class="page-header">Header</div>
                </div>
            </div>
        </div>        
    </header>
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-md-2">
                @{ 
                    Html.RenderAction("Navigation", "Product");
                }
            </div>
            <div class="col-xs-12 col-md-10">   
                @{Html.RenderAction("SummaryCart", "Cart");}
                             
                @RenderBody()
            </div>
        </div>        
    </div>
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <p>Bản quyền &copy; 2017 - vanvuong2610@@gmail.com - Học viện MSITA</p>
                </div>
            </div>
        </div>          
    </footer>
    <!--Javascript Library-->
    <script src="~/Scripts/jquery-3.1.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    @RenderSection("js", false)
</body>
</html>