Entities/Product.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace WebApplication1.Entities
{
    public class Product
    {
        [Key]
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public decimal Price { get; set; }
        public int Amount { get; set; }
        public int CategoryId { get; set; }

        public virtual Category Category { get; set; }

        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public Product()
        {
            OrderDetails = new HashSet<OrderDetail>();
        }
    }
}

Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Abstract;
using WebApplication1.Entities;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class CartController : Controller
    {
        private IProductRepository productRepository;
        private IOrderProcessor orderProcessor;

        public CartController(IProductRepository repo, IOrderProcessor orderPara)
        {
            productRepository = repo;
            orderProcessor = orderPara;
        }
        
        public RedirectToRouteResult AddToCart(Cart cart, int productId, string returnUrl)
        {
            Product product = productRepository.Products
                .FirstOrDefault(p => p.ProductId == productId);

            if (product != null)
            {
                cart.AddItem(product, 1);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToRouteResult RemoveFromCart(Cart cart, int productId, string returnUrl)
        {
            Product product = productRepository.Products
                .FirstOrDefault(p => p.ProductId == productId);

            if (product != null)
            {
                cart.RemoveLine(product);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public PartialViewResult SummaryCart(Cart cart)
        {
            return PartialView(cart);
        }

        public ViewResult Index(Cart cart, string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }

        [HttpPost]
        public ActionResult UpdateQuantity(Cart cart, int productId , int quantity, string returnUrl)        
        {
            cart.UpdateQuantityByProductID(new Product { ProductId = productId }, quantity);
            return RedirectToAction("Index", new { returnUrl });
        }

        public ViewResult Checkout()
        {
            return View(new ShippingDetails());
        }

        [HttpPost]
        public ActionResult Checkout(Cart cart, ShippingDetails shippingDetails)
        {
            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Vui lòng chọn thêm sản phẩm");
            }

            if (ModelState.IsValid)
            {
                //Xử lý đơn hàng: Lưu vào CSDL, gửi email
                orderProcessor.ProcessOrder(cart, shippingDetails);
                //xóa thông tin giỏ hàng
                cart.Clear();
                //chuyển người dùng đến view thông báo hoàn tất đặt hàng
                return View("Completed");
            }
            else
            {
                return View(shippingDetails);
            }
        }        
    }
}

Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Abstract;
using WebApplication1.Concrete;
using WebApplication1.Entities;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class ProductController : Controller
    {
        private IProductRepository productRepository { get; set; }

        public ProductController(IProductRepository productRepoPara)
        {
            productRepository = productRepoPara;
        }

        public ViewResult Index(int page = 1, int categoryId = 0)
        {
            int pageSize = 1;

            ProductIndexViewModel model = new ProductIndexViewModel();
            model.Products = productRepository.Products
                .Where(x => categoryId == 0 || x.CategoryId == categoryId)
                .OrderByDescending(x=>x.ProductId)
                .Skip((page - 1) * pageSize)
                .Take(pageSize)
                .ToList();

            model.PagingInfo = new PagingInfo()
            {
                CurrentPage = page,
                ItemsPerPage = pageSize,
                TotalItems = productRepository.Products
                .Where(x=> categoryId == 0 || x.CategoryId == categoryId).Count()
            };

            model.CurrentCategory = categoryId;

            return View(model);
        }

        public ViewResult Detail(int productId)
        {
            Product product = productRepository
                .Products
                .FirstOrDefault(x => x.ProductId == productId);

            if(product == null)
            {
                return View("NotFound");
            }

            return View(product);
        }

        public PartialViewResult Navigation()
        {
            List<Category> categories = productRepository.Categories.ToList();
            return PartialView(categories);
        }


    }
}

Views/Product/Detail.cshtml
@model WebApplication1.Entities.Product
@{
    ViewBag.Title = "Detail";
    Layout = "~/Views/Shared/_LayoutHome.cshtml";
}
<div class="page-header">
    <h1>
        Chi tiết sản phẩm: @Model.ProductName
    </h1>    
</div>
<ul>
    <li>Mã sản phẩm: @Model.ProductId</li>
    <li>Đơn giá: @Model.Price</li>
    <li>Tình trạng: @(Model.Amount > 0 ? "Còn hàng" : "Hết hàng")</li>
    <li>Danh mục: @Model.Category.CategoryName</li>
</ul>

Views/Product/Index.cshtml
@model WebApplication1.Models.ProductIndexViewModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutHome.cshtml";
}
<div class="page-header">
    <h1>Danh sách sản phẩm</h1>
</div>
<table class="table table-striped">
    <tr>
        <td>Mã sản phẩm</td>
        <td>Tên sản phẩm</td>
        <td>Giá tiền</td>
        <td>Danh mục</td>
        <td>&nbsp;</td>
    </tr>
    @foreach (var product in Model.Products)
    {
        <tr>
            <td>@product.ProductId</td>
            <td>@product.ProductName</td>
            <td>@product.Price</td>
            <td>@product.Category.CategoryName</td>
            <td>
                <div class="row">
                    <div class="col-xs-12 col-md-6">
                        <a href="@Url.Action("Detail","Product", new { productId = product.ProductId })"
                           class="btn btn-primary">
                            <i class="glyphicon glyphicon-search"></i>
                            Chi tiết
                        </a>
                    </div>
                    <div class="col-xs-12 col-md-6">
                        @using (Html.BeginForm("AddToCart", "Cart", FormMethod.Post, new { @class = "frmAddToCart" }))
                        {
                            <input name="ProductId" value="@product.ProductId" type="hidden" />
                            @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
                            <button type="submit" class="btn btn-danger">
                                <i class="glyphicon glyphicon-shopping-cart"></i>
                                Thêm vào giỏ hàng
                            </button>
                        }
                    </div>
                </div>                               
            </td>
        </tr>
    }
    <tr>
        <td colspan="5" class="text-center"> 
            <nav>
                <ul class="pagination">
                    @Html.PageLinks(Model.PagingInfo, x => Url.Action("Index",
                        new
                        {
                            page = x,
                            categoryId = Model.CurrentCategory
                        }))
                </ul>
            </nav>
        </td>
    </tr>
</table>

Views/Product/Navigation.cshtml
@model List<WebApplication1.Entities.Category>

<ul class="list-group list-group-item-success">
    <li class="list-group-item">
        <a href="@Url.Action("Index", "Product")">
            Tất cả
        </a>
    </li>
    @foreach(var category in Model)
    {
        <li class="list-group-item">
            <a href="@Url.Action("Index", "Product", new { categoryId = category.CategoryId})">
                @category.CategoryName
            </a>
        </li>
    }
</ul>

Views/Product/NotFound.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <div>
    
    </div>
</body>
</html>